DROP TABLE IF EXISTS demo."Accomodations" CASCADE;
DROP TABLE IF EXISTS demo."CitiesCountries" CASCADE;
DROP TABLE IF EXISTS demo."Cities" CASCADE;
DROP TABLE IF EXISTS demo."HotelChains" CASCADE;
DROP TABLE IF EXISTS demo."AccomodationTypes" CASCADE;
DROP TABLE IF EXISTS demo."Countries" CASCADE;
DROP TABLE IF EXISTS demo."Continents" CASCADE;

DROP SCHEMA IF EXISTS demo CASCADE;