DROP TABLE IF EXISTS d101."Accomodations" CASCADE;
DROP TABLE IF EXISTS d101."Cities" CASCADE;
DROP TABLE IF EXISTS d101."HotelChains" CASCADE;
DROP TABLE IF EXISTS d101."AccomodationTypes" CASCADE;
DROP TABLE IF EXISTS d101."Countries" CASCADE;
DROP TABLE IF EXISTS d101."Continents" CASCADE;

DROP SCHEMA IF EXISTS d101 CASCADE;